export const GET_JOKE_CATEGORIES = 'GET_JOKE_CATEGORIES'
export const SET_TEST_VALUE = 'SET_TEST_VALUE'
export const SET_JOKE = 'SET_JOKE'
export const SET_JOKE_TYPE = 'SET_JOKE_TYPE'
export const INPUT_VALUE = 'INPUT_VALUE'
export const SET_CATEGORY = 'SET_CATEGORY'
export const SET_CATEGORY_ERROR_MESSAGE = 'SET_CATEGORY_ERROR_MESSAGE'
export const SET_SEARCH_ERROR_MESSAGE = 'SET_SEARCH_ERROR_MESSAGE'
export const SET_FAV_JOKE = 'SET_FAV_JOKE'
export default {
  GET_JOKE_CATEGORIES,
  SET_TEST_VALUE, 
  SET_JOKE, 
  SET_JOKE_TYPE, 
  SET_CATEGORY, 
  SET_CATEGORY_ERROR_MESSAGE, 
  SET_SEARCH_ERROR_MESSAGE,
  SET_FAV_JOKE
};